version: "3.8"

services:
  app:
    image: yashs3324/malfoy:latest
    container_name: malfoy-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://neondb_owner:npg_Qhnv9WSDl2fj@ep-muddy-voice-a494z8vq-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
      - NEXTAUTH_URL=https://malfoy.yashprojects.online
      - NEXTAUTH_SECRET=QrFHKjWVmNx9Bc8h7tA5vEzP3dY6UeJZ
      - JWT_SECRET=L7R5tQp2ZxK9WjS8bC1vE3mD6nH4gY7y
      - NEXT_PUBLIC_API_URL=https://malfoy.yashprojects.online
      - EMAIL_SERVER_HOST=smtp.gmail.com
      - EMAIL_SERVER_PORT=465
      - EMAIL_SERVER_USER=yashs3324@gmail.com
      - EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD}
      - EMAIL_FROM=yashs3324@gmail.com
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - APPLE_CLIENT_ID=${APPLE_CLIENT_ID}
      - APPLE_TEAM_ID=${APPLE_TEAM_ID}
      - APPLE_KEY_ID=${APPLE_KEY_ID}
      - APPLE_PRIVATE_KEY=${APPLE_PRIVATE_KEY}
      - NEXT_PUBLIC_APPLE_CLIENT_ID=${APPLE_CLIENT_ID}
    networks:
      - malfoy-network

  # Add development setup for easier local development
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: malfoy-dev
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - malfoy-network

volumes:
  app-data:

networks:
  malfoy-network:
    driver: bridge
