export const marketZones = [
    {
      id: 1,
      name: "Premium Market",
      price: "High",
      competitors: 3,
      opportunity: "Medium",
      className: "col-span-2 row-span-1 bg-blue-100",
      gridPosition: "col-span-2 row-span-1",
      textColor: "text-blue-800",
    },
    {
      id: 2,
      name: "Value Market",
      price: "Medium",
      competitors: 8,
      opportunity: "Low",
      className: "bg-yellow-100",
      gridPosition: "col-span-2 row-span-1",
      textColor: "text-yellow-800",
      indicators: [{ color: "#4F46E5" }, { color: "#4F46E5", opacity: 0.8 }],
    },
    {
      id: 3,
      name: "Budget Market",
      price: "Low",
      competitors: 5,
      opportunity: "Medium",
      className: "bg-red-100",
      gridPosition: "col-span-1 row-span-1",
      textColor: "text-red-800",
    },
    {
      id: 4,
      name: "Luxury Market",
      price: "Very High",
      competitors: 2,
      opportunity: "High",
      className: "bg-green-100",
      gridPosition: "col-span-2 row-span-2",
      textColor: "text-green-800",
      indicators: [{ color: "#22C55E" }],
    },
    {
      id: 5,
      name: "Mass Market",
      price: "Medium-Low",
      competitors: 12,
      opportunity: "Medium",
      className: "bg-orange-100",
      gridPosition: "col-span-1 row-span-1",
      textColor: "text-orange-800",
    },
  ];

  // Define timeline points for competitor timeline
 export const timelinePoints = [
    {
      id: 0,
      date: "Jan 12, 2025",
      description: "No significant changes",
      isHighlighted: false,
    },
    {
      id: 1,
      date: "Feb 03, 2025",
      description: "No significant changes",
      isHighlighted: false,
    },
    {
      id: 2,
      date: "Feb 27, 2025",
      description: "Competitor A dropped prices by 15%",
      isHighlighted: true,
    },
    {
      id: 3,
      date: "Mar 15, 2025",
      description: "No significant changes",
      isHighlighted: false,
    },
    {
      id: 4,
      date: "Apr 02, 2025",
      description: "Competitor B increased prices by 8%",
      isHighlighted: true,
    },
    {
      id: 5,
      date: "Apr 17, 2025",
      description: "No significant changes",
      isHighlighted: false,
    },
  ];

export const radarData = [
  {
    name: "Quality",
    Your_Product: 80,
    Premium_Market: 90,
    Value_Market: 60,
    Budget_Market: 40,
    Luxury_Market: 95,
  },
  {
    name: "Price",
    Your_Product: 65,
    Premium_Market: 75,
    Value_Market: 55,
    Budget_Market: 30,
    Luxury_Market: 90,
  },
  {
    name: "Features",
    Your_Product: 75,
    Premium_Market: 85,
    Value_Market: 60,
    Budget_Market: 35,
    Luxury_Market: 95,
  },
  {
    name: "Support",
    Your_Product: 85,
    Premium_Market: 80,
    Value_Market: 60,
    Budget_Market: 40,
    Luxury_Market: 90,
  },
  {
    name: "Brand",
    Your_Product: 70,
    Premium_Market: 85,
    Value_Market: 65,
    Budget_Market: 40,
    Luxury_Market: 95,
  },
  {
    name: "Market Share",
    Your_Product: 60,
    Premium_Market: 70,
    Value_Market: 75,
    Budget_Market: 60,
    Luxury_Market: 45,
  },
];
